services:
  _defaults:
    autowire: true
    autoconfigure: true

  Kowada\AuthBundle\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/KowadaAuthBundle.php'
